# Site
repository: ljg294/ljg294.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 이재규
title: Software Engineer
email: ljg29494@gmail.com
# email_title: Email (Email title override)
phone: +82-10-9651-2425
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: ljg294
linkedin_username: jay-gue-lee-b7065a194

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  **Deal with it**<br/>
  4년 차 백엔드 엔지니어 입니다. (상품, 주문, 쿠폰, 회원)<br/>
  Java & Spring, Cloud(AWS) 기반으로 API 개발을 했습니다.<br/>
  <mark>단독</mark>으로도 도메인 개발을 주도 한적도 있고, 팀원과 <mark>협력</mark>하여 도메인 개발을 진행한 적도 있습니다.<br/>
  <br/>
  <mark>DevOps</mark>에 관심이 생겨 Operation skill-set에 관심을 두고 있습니다.<br/>
  직장 업무를 우선으로 하나 세미나, 소모임 적극적인 참석 등 외부 활동에 관심이 많습니다.<br/>
  OpenInfra Community Days Korea 2023에 contribute 한 경험이 있습니다.<br/>
  [개발자 관점에서 보는 웹 애플리케이션과 쿠버네티스](https://youtu.be/wsmsFl3cMzY?si=eQxCO-5gB2sNJsrp)<br/>

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        border: weak  # Value of `weak` will display a weak border below this item. # Any
#        # other value (or no value) means no border will be displayed
#        title: Project name
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
#        additional_links:
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        quote: >
#          Short overview of the project (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description about the work on/with the project

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
